name: 📕 Documentation Issue
description: If you found an issue on sensoroui.xingkang.wang website
title: "docs: "
body:
  - type: markdown
    attributes:
      value: |
        Please first search in [existing issues](https://github.com/sensoro/sensoro-ui/issues?q=is%3Aissue) and [discussion forum](https://github.com/sensoro/sensoro-ui/discussions) and make sure this issue is not addressed before.
  - type: input
    id: page
    attributes:
      label: On which page do you see this issue?
      placeholder: "example: https://sensoroui.xingkang.wang/"
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: Describe the problem and say how and when it happens
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - All browsers
        - Chrome
        - Chrome Android
        - Safari
        - Safari iOS
        - Firefox
        - Edge
        - Other
